## 3. 웹 스크래핑

In [1]:
import pandas as pd
from pandas import DataFrame, Series

### 1) read_clipboard() - 복사(ctrl C) 붙여넣기(ctrl V)

In [12]:
# 2. chromedriver 다운로드하여 적절한 위치에 옮기기
# 다운로드 사이트: https://sites.google.com/a/chromium.org/chromedriver/downloads
# 자신의 크롬 브라우저의 버전에 맞는 파일을 다운로드
코스피 = pd.read_clipboard()
코스피

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
0,1,삼성전자,"79,800",하락 800,-0.99%,100,"4,763,886","5,969,783",53.49,"10,782,325",19.16,9.99,토론실
1,2,SK하이닉스,"121,500","하락 2,000",-1.62%,"5,000","884,523","728,002",49.11,"2,898,638",17.35,9.53,토론실
2,3,NAVER,"447,000","하락 2,000",-0.45%,100,"734,257","164,263",56.93,"1,242,657",4.55,15.22,토론실
3,4,카카오,"157,000","하락 2,500",-1.57%,100,"697,803","444,460",31.96,"3,385,574",228.53,2.70,토론실
4,5,삼성전자우,"72,900",하락 200,-0.27%,100,"599,884","822,887",75.59,"713,233",17.50,NaN,토론실
5,6,삼성바이오로직스,"899,000","상승 25,000",+2.86%,"2,500","594,823","66,165",10.15,"233,246",224.19,NaN,토론실
6,7,LG화학,"828,000","상승 10,000",+1.22%,"5,000","584,505","70,592",46.82,"215,077",36.04,2.93,토론실
7,8,삼성SDI,"749,000","하락 1,000",-0.13%,"5,000","515,046","68,765",43.47,"151,644",73.37,4.54,토론실
8,9,현대차,"230,000","하락 1,500",-0.65%,"5,000","491,437","213,668",29.33,"465,029",27.83,2.04,토론실
9,10,셀트리온,"269,000","상승 2,500",+0.94%,"1,000","370,995","137,917",20.38,"561,139",61.71,16.68,토론실
10,11,기아,"87,100","하락 1,100",-1.25%,"5,000","353,071","405,363",33.50,"1,336,465",15.65,5.05,토론실
11,12,POSCO,"341,000","하락 5,000",-1.45%,"5,000","297,307","87,187",53.92,"362,071",13.32,3.61,토론실
12,13,현대모비스,"284,500","하락 2,000",-0.70%,"5,000","269,686","94,793",36.50,"119,489",15.18,4.66,토론실
13,14,LG생활건강,"1,713,000","상승 14,000",+0.82%,"5,000","267,540","15,618",46.56,"16,928",36.92,17.92,토론실
14,15,LG전자,"160,500",하락 500,-0.31%,"5,000","262,655","163,648",31.05,"517,931",14.95,13.23,토론실
15,16,삼성물산,"134,500",0,0.00%,100,"251,363","186,887",14.83,"205,952",16.02,3.81,토론실
16,17,SK이노베이션,"262,500","하락 4,500",-1.69%,"5,000","242,722","92,466",23.25,"670,675",-24.82,-13.58,토론실
17,18,SK텔레콤,"322,000","상승 2,000",+0.63%,500,"232,034","72,060",46.17,"110,134",14.83,6.44,토론실
18,19,KB금융,"52,500",상승 700,+1.35%,"5,000","218,299","415,808",67.69,"1,121,892",5.46,8.53,토론실
19,20,신한지주,"38,750",상승 50,+0.13%,"5,000","200,182","516,600",60.40,"1,479,410",5.44,8.20,토론실
20,21,SK,"277,500",하락 500,-0.18%,200,"195,250","70,360",20.20,"101,219",32.32,1.11,토론실
21,22,엔씨소프트,"839,000","상승 35,000",+4.35%,500,"184,194","21,954",51.45,"215,064",38.96,20.83,토론실
22,23,HMM,"43,950",상승 850,+1.97%,"5,000","178,170","405,392",10.11,"5,193,000",41.66,8.93,토론실
23,24,한국전력,"25,050",0,0.00%,"5,000","160,812","641,964",15.44,"1,938,893",7.83,2.91,토론실
24,25,LG,"98,800",하락 600,-0.60%,"5,000","155,413","157,301",33.35,"293,271",9.07,7.50,토론실
25,26,삼성생명,"77,300",상승 400,+0.52%,500,"154,600","200,000",13.32,"213,961",7.28,3.53,토론실
26,27,SK아이이테크놀로지,"213,000","상승 8,500",+4.16%,"1,000","151,864","71,298",7.07,"762,420",NaN,11.00,토론실
27,28,삼성에스디에스,"185,500","하락 1,000",-0.54%,500,"143,536","77,378",11.93,"95,893",22.81,6.71,토론실
28,29,아모레퍼시픽,"244,500",하락 500,-0.20%,500,"142,931","58,458",33.70,"88,958",171.10,0.78,토론실
29,30,삼성전기,"188,500",0,0.00%,"5,000","140,798","74,694",31.71,"500,558",20.74,10.92,토론실
30,31,하나금융지주,"43,800",0,0.00%,"5,000","131,506","300,242",68.19,"840,676",4.67,8.96,토론실
31,32,포스코케미칼,"165,000",상승 500,+0.30%,500,"127,814","77,463",8.16,"492,856",198.32,2.96,토론실
32,33,하이브,"317,500","하락 2,000",-0.63%,500,"123,834","39,003",14.30,"225,619",112.95,12.52,토론실
33,34,SK바이오사이언스,"158,500","상승 4,000",+2.59%,500,"121,252","76,500",3.52,"486,310",123.15,13.25,토론실
34,35,넷마블,"140,000","상승 2,000",+1.45%,100,"120,335","85,954",22.95,"429,508",38.08,6.35,토론실
35,36,KT&G,"83,700",상승 300,+0.36%,"5,000","114,914","137,292",37.65,"263,141",9.97,13.22,토론실
36,37,S-Oil,"98,800","하락 2,700",-2.66%,"2,500","111,232","112,583",77.74,"642,115",26.84,-13.07,토론실
37,38,대한항공,"30,900",상승 100,+0.32%,"5,000","107,477","347,821",10.83,"1,243,583",13.21,-7.22,토론실
38,39,두산중공업,"25,100",하락 950,-3.65%,"5,000","107,347","427,676",8.14,"7,501,736",-14.10,-37.20,토론실
39,40,삼성화재,"221,500","상승 1,500",+0.68%,500,"104,935","47,375",48.34,"50,568",11.04,4.96,토론실
40,41,SK바이오팜,"125,500","하락 3,000",-2.33%,500,"98,283","78,313",6.90,"324,700",-182.15,-135.18,토론실
41,42,롯데케미칼,"270,000","상승 1,500",+0.56%,"5,000","92,544","34,275",26.64,"114,273",12.47,1.22,토론실
42,43,고려아연,"489,000","하락 6,000",-1.21%,"5,000","92,274","18,870",21.05,"76,063",14.31,8.37,토론실
43,44,한국조선해양,"126,000","하락 1,500",-1.18%,"5,000","89,174","70,773",17.58,"222,850",-9.64,-7.42,토론실
44,45,한온시스템,"16,250",0,0.00%,100,"86,742","533,800",18.39,"1,127,721",64.23,5.09,토론실
45,46,KT,"33,050",상승 50,+0.15%,"5,000","86,297","261,112",44.32,"635,192",11.47,4.76,토론실
46,47,LG디스플레이,"23,250",하락 300,-1.27%,"5,000","83,192","357,816",19.20,"1,634,751",24.63,-0.79,토론실
47,48,우리금융지주,"11,350",0,0.00%,"5,000","81,977","722,268",25.75,"1,042,614",5.63,5.87,토론실
48,49,한화솔루션,"42,850",상승 100,+0.23%,"5,000","81,963","191,278",17.24,"634,245",11.49,5.30,토론실
49,50,기업은행,"10,450",상승 100,+0.97%,"5,000","77,779","744,301",12.80,"1,402,464",5.12,6.44,토론실

### 2) read_html() - html 문서 내 테이블 데이터 읽어오기

In [13]:
data = pd.read_html('https://finance.naver.com/sise/sise_market_sum.nhn',encoding='cp949')

In [14]:
df = data[1]

In [15]:
#NA값 제거
df[df.종목명.notnull()]

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,1.0,삼성전자,79800.0,800.0,-0.99%,100.0,4763886.0,5969783.0,53.49,10782325.0,19.16,9.99,NaN
2,2.0,SK하이닉스,121500.0,2000.0,-1.62%,5000.0,884523.0,728002.0,49.11,2898638.0,17.35,9.53,NaN
3,3.0,NAVER,447000.0,2000.0,-0.45%,100.0,734257.0,164263.0,56.93,1242657.0,4.55,15.22,NaN
4,4.0,카카오,157000.0,2500.0,-1.57%,100.0,697803.0,444460.0,31.96,3385574.0,228.53,2.70,NaN
5,5.0,삼성전자우,72900.0,200.0,-0.27%,100.0,599884.0,822887.0,75.59,713233.0,17.50,NaN,NaN
9,6.0,삼성바이오로직스,899000.0,25000.0,+2.86%,2500.0,594823.0,66165.0,10.15,233246.0,224.19,NaN,NaN
10,7.0,LG화학,828000.0,10000.0,+1.22%,5000.0,584505.0,70592.0,46.82,215077.0,36.04,2.93,NaN
11,8.0,삼성SDI,749000.0,1000.0,-0.13%,5000.0,515046.0,68765.0,43.47,151644.0,73.37,4.54,NaN
12,9.0,현대차,230000.0,1500.0,-0.65%,5000.0,491437.0,213668.0,29.33,465029.0,27.83,2.04,NaN
13,10.0,셀트리온,269000.0,2500.0,+0.94%,1000.0,370995.0,137917.0,20.38,561139.0,61.71,16.68,NaN
17,11.0,기아,87100.0,1100.0,-1.25%,5000.0,353071.0,405363.0,33.50,1336465.0,15.65,5.05,NaN
18,12.0,POSCO,341000.0,5000.0,-1.45%,5000.0,297307.0,87187.0,53.92,362071.0,13.32,3.61,NaN
19,13.0,현대모비스,284500.0,2000.0,-0.70%,5000.0,269686.0,94793.0,36.50,119489.0,15.18,4.66,NaN
20,14.0,LG생활건강,1713000.0,14000.0,+0.82%,5000.0,267540.0,15618.0,46.56,16928.0,36.92,17.92,NaN
21,15.0,LG전자,160500.0,500.0,-0.31%,5000.0,262655.0,163648.0,31.05,517931.0,14.95,13.23,NaN
25,16.0,삼성물산,134500.0,0.0,0.00%,100.0,251363.0,186887.0,14.83,205952.0,16.02,3.81,NaN
26,17.0,SK이노베이션,262500.0,4500.0,-1.69%,5000.0,242722.0,92466.0,23.25,670675.0,-24.82,-13.58,NaN
27,18.0,SK텔레콤,322000.0,2000.0,+0.63%,500.0,232034.0,72060.0,46.17,110134.0,14.83,6.44,NaN
28,19.0,KB금융,52500.0,700.0,+1.35%,5000.0,218299.0,415808.0,67.69,1121892.0,5.46,8.53,NaN
29,20.0,신한지주,38750.0,50.0,+0.13%,5000.0,200182.0,516600.0,60.40,1479410.0,5.44,8.20,NaN
33,21.0,SK,277500.0,500.0,-0.18%,200.0,195250.0,70360.0,20.20,101219.0,32.32,1.11,NaN
34,22.0,엔씨소프트,839000.0,35000.0,+4.35%,500.0,184194.0,21954.0,51.45,215064.0,38.96,20.83,NaN
35,23.0,HMM,43950.0,850.0,+1.97%,5000.0,178170.0,405392.0,10.11,5193000.0,41.66,8.93,NaN
36,24.0,한국전력,25050.0,0.0,0.00%,5000.0,160812.0,641964.0,15.44,1938893.0,7.83,2.91,NaN
37,25.0,LG,98800.0,600.0,-0.60%,5000.0,155413.0,157301.0,33.35,293271.0,9.07,7.50,NaN
41,26.0,삼성생명,77300.0,400.0,+0.52%,500.0,154600.0,200000.0,13.32,213961.0,7.28,3.53,NaN
42,27.0,SK아이이테크놀로지,213000.0,8500.0,+4.16%,1000.0,151864.0,71298.0,7.07,762420.0,NaN,11.00,NaN
43,28.0,삼성에스디에스,185500.0,1000.0,-0.54%,500.0,143536.0,77378.0,11.93,95893.0,22.81,6.71,NaN
44,29.0,아모레퍼시픽,244500.0,500.0,-0.20%,500.0,142931.0,58458.0,33.70,88958.0,171.10,0.78,NaN
45,30.0,삼성전기,188500.0,0.0,0.00%,5000.0,140798.0,74694.0,31.71,500558.0,20.74,10.92,NaN
49,31.0,하나금융지주,43800.0,0.0,0.00%,5000.0,131506.0,300242.0,68.19,840676.0,4.67,8.96,NaN
50,32.0,포스코케미칼,165000.0,500.0,+0.30%,500.0,127814.0,77463.0,8.16,492856.0,198.32,2.96,NaN
51,33.0,하이브,317500.0,2000.0,-0.63%,500.0,123834.0,39003.0,14.30,225619.0,112.95,12.52,NaN
52,34.0,SK바이오사이언스,158500.0,4000.0,+2.59%,500.0,121252.0,76500.0,3.52,486310.0,123.15,13.25,NaN
53,35.0,넷마블,140000.0,2000.0,+1.45%,100.0,120335.0,85954.0,22.95,429508.0,38.08,6.35,NaN
57,36.0,KT&G,83700.0,300.0,+0.36%,5000.0,114914.0,137292.0,37.65,263141.0,9.97,13.22,NaN
58,37.0,S-Oil,98800.0,2700.0,-2.66%,2500.0,111232.0,112583.0,77.74,642115.0,26.84,-13.07,NaN
59,38.0,대한항공,30900.0,100.0,+0.32%,5000.0,107477.0,347821.0,10.83,1243583.0,13.21,-7.22,NaN
60,39.0,두산중공업,25100.0,950.0,-3.65%,5000.0,107347.0,427676.0,8.14,7501736.0,-14.10,-37.20,NaN
61,40.0,삼성화재,221500.0,1500.0,+0.68%,500.0,104935.0,47375.0,48.34,50568.0,11.04,4.96,NaN
65,41.0,SK바이오팜,125500.0,3000.0,-2.33%,500.0,98283.0,78313.0,6.90,324700.0,-182.15,-135.18,NaN
66,42.0,롯데케미칼,270000.0,1500.0,+0.56%,5000.0,92544.0,34275.0,26.64,114273.0,12.47,1.22,NaN
67,43.0,고려아연,489000.0,6000.0,-1.21%,5000.0,92274.0,18870.0,21.05,76063.0,14.31,8.37,NaN
68,44.0,한국조선해양,126000.0,1500.0,-1.18%,5000.0,89174.0,70773.0,17.58,222850.0,-9.64,-7.42,NaN
69,45.0,한온시스템,16250.0,0.0,0.00%,100.0,86742.0,533800.0,18.39,1127721.0,64.23,5.09,NaN
73,46.0,KT,33050.0,50.0,+0.15%,5000.0,86297.0,261112.0,44.32,635192.0,11.47,4.76,NaN
74,47.0,LG디스플레이,23250.0,300.0,-1.27%,5000.0,83192.0,357816.0,19.20,1634751.0,24.63,-0.79,NaN
75,48.0,우리금융지주,11350.0,0.0,0.00%,5000.0,81977.0,722268.0,25.75,1042614.0,5.63,5.87,NaN
76,49.0,한화솔루션,42850.0,100.0,+0.23%,5000.0,81963.0,191278.0,17.24,634245.0,11.49,5.30,NaN
77,50.0,기업은행,10450.0,100.0,+0.97%,5000.0,77779.0,744301.0,12.80,1402464.0,5.12,6.44,NaN

In [17]:
#1페이지~ 중 10개의 페이지만 읽어 합치기
#시가 총액이 높은 상위 500개 기업의 데이터 읽어오기
#https://finance.naver.com/sise/sise_market_sum.nhn?&page=1 ~10 까지
코스피500 = []
url='https://finance.naver.com/sise/sise_market_sum.nhn?&page='
for num in range(1,11):
    full_url = url + str(num)
    data = pd.read_html(full_url,encoding='cp949')
    df = data[1]
    df = df[df.종목명.notnull()]
    코스피500.append(df)

In [18]:
코스피500[9]

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,451.0,SNT중공업,10850.0,100.0,+0.93%,2500.0,3608.0,33253.0,8.10,56179.0,6.07,1.37,NaN
2,452.0,유양디앤유,2440.0,0.0,0.00%,500.0,3593.0,147236.0,1.17,0.0,-11.79,-64.02,NaN
3,453.0,제일파마홀딩스,22450.0,0.0,0.00%,500.0,3586.0,15973.0,9.89,6865.0,43.93,2.86,NaN
4,454.0,KBSTAR KIS종합채권(A-이상)액티브,100635.0,145.0,+0.14%,0.0,3580.0,3557.0,0.00,6.0,NaN,NaN,NaN
5,455.0,화신,10250.0,100.0,-0.97%,500.0,3579.0,34920.0,2.10,546723.0,-31.54,-19.53,NaN
9,456.0,케이씨,26400.0,50.0,-0.19%,500.0,3578.0,13554.0,7.61,50300.0,8.35,9.19,NaN
10,457.0,코스모화학,12850.0,50.0,+0.39%,1000.0,3553.0,27653.0,1.49,992341.0,-19.56,-19.42,NaN
11,458.0,코리아써키트,14950.0,100.0,+0.67%,500.0,3531.0,23621.0,3.32,862585.0,39.66,3.39,NaN
12,459.0,KBSTAR ESG사회책임투자,14205.0,75.0,-0.53%,0.0,3516.0,24750.0,0.18,128125.0,NaN,NaN,NaN
13,460.0,현대에너지솔루션,31150.0,100.0,+0.32%,5000.0,3489.0,11200.0,1.88,28398.0,117.11,1.93,NaN
17,461.0,대원제약,16350.0,50.0,+0.31%,500.0,3470.0,21225.0,16.72,27043.0,163.50,8.42,NaN
18,462.0,현대비앤지스틸,22650.0,250.0,+1.12%,5000.0,3415.0,15079.0,4.89,1242715.0,9.05,5.68,NaN
19,463.0,한화3우B,15100.0,0.0,0.00%,5000.0,3393.0,22472.0,9.14,44658.0,3.87,NaN,NaN
20,464.0,KINDEX 200TR,26500.0,135.0,-0.51%,0.0,3392.0,12800.0,0.01,528.0,NaN,NaN,NaN
21,465.0,사조산업,67500.0,0.0,0.00%,5000.0,3375.0,5000.0,4.56,32419.0,17.65,1.85,NaN
25,466.0,SBS미디어홀딩스,2410.0,60.0,+2.55%,500.0,3371.0,139896.0,2.25,11978097.0,-6.64,-11.93,NaN
26,467.0,신도리코,33400.0,350.0,+1.06%,5000.0,3367.0,10080.0,19.58,17875.0,392.94,-1.56,NaN
27,468.0,무림P&P,5370.0,30.0,+0.56%,2500.0,3349.0,62368.0,2.17,180362.0,-25.57,-1.43,NaN
28,469.0,서연,14250.0,400.0,-2.73%,500.0,3346.0,23480.0,1.21,347333.0,180.38,-1.26,NaN
29,470.0,SNT홀딩스,20450.0,250.0,-1.21%,500.0,3334.0,16304.0,11.15,8709.0,4.98,4.62,NaN
33,471.0,경보제약,13800.0,500.0,-3.50%,500.0,3299.0,23907.0,0.95,227837.0,37.00,6.16,NaN
34,472.0,세아제강지주,78900.0,1800.0,-2.23%,5000.0,3268.0,4142.0,5.37,6030.0,11.95,1.76,NaN
35,473.0,삼화페인트,12000.0,200.0,-1.64%,500.0,3264.0,27203.0,9.43,86535.0,34.99,2.29,NaN
36,474.0,이수화학,12000.0,50.0,-0.41%,5000.0,3261.0,27178.0,1.99,159157.0,-3.39,-31.08,NaN
37,475.0,종근당바이오,59100.0,900.0,-1.50%,2500.0,3242.0,5486.0,1.03,41459.0,182.97,3.79,NaN
41,476.0,KODEX 코스피,32870.0,190.0,-0.57%,0.0,3221.0,9800.0,0.01,50294.0,NaN,NaN,NaN
42,477.0,동부건설,14150.0,200.0,-1.39%,5000.0,3216.0,22726.0,2.53,76022.0,6.80,10.10,NaN
43,478.0,KPX케미칼,65900.0,200.0,+0.30%,5000.0,3190.0,4840.0,30.12,2707.0,4.43,12.70,NaN
44,479.0,JW홀딩스,4645.0,20.0,+0.43%,500.0,3179.0,68441.0,2.51,132170.0,16.53,7.45,NaN
45,480.0,계룡건설,35200.0,150.0,-0.42%,5000.0,3144.0,8931.0,24.30,20684.0,3.09,18.69,NaN
49,481.0,유니퀘스트,11500.0,100.0,-0.86%,500.0,3143.0,27329.0,44.91,118435.0,8.75,10.80,NaN
50,482.0,삼성전기우,108000.0,500.0,-0.46%,5000.0,3140.0,2907.0,10.31,15448.0,11.89,NaN,NaN
51,483.0,신세계 I&C,182500.0,3000.0,+1.67%,5000.0,3139.0,1720.0,2.89,8416.0,4.29,33.89,NaN
52,484.0,아모레G3우(전환),43950.0,100.0,+0.23%,500.0,3117.0,7092.0,7.17,785.0,86.18,NaN,NaN
53,485.0,벽산,4545.0,70.0,-1.52%,500.0,3116.0,68560.0,4.39,965511.0,-505.00,-0.67,NaN
57,486.0,경농,15850.0,0.0,0.00%,500.0,3094.0,19523.0,1.45,62022.0,24.80,6.70,NaN
58,487.0,동성케미컬,6220.0,0.0,0.00%,1000.0,3091.0,49690.0,4.02,44234.0,67.61,2.39,NaN
59,488.0,백광산업,6840.0,150.0,-2.15%,500.0,3072.0,44918.0,2.38,952540.0,27.69,5.89,NaN
60,489.0,광주신세계,192000.0,8000.0,+4.35%,5000.0,3072.0,1600.0,12.25,2386.0,6.69,6.35,NaN
61,490.0,STX엔진,13300.0,200.0,-1.48%,2500.0,3060.0,23009.0,0.00,60185.0,22.70,8.19,NaN
65,491.0,금호에이치티,2435.0,5.0,+0.21%,500.0,3050.0,125258.0,2.18,1817555.0,-65.81,-4.85,NaN
66,492.0,세아제강,107500.0,1000.0,-0.92%,5000.0,3049.0,2836.0,7.86,7080.0,10.86,5.67,NaN
67,493.0,도화엔지니어링,9010.0,20.0,-0.22%,500.0,3038.0,33720.0,2.03,37924.0,21.56,7.00,NaN
68,494.0,TIGER 차이나CSI300,11960.0,80.0,-0.66%,0.0,3038.0,25400.0,0.70,114268.0,NaN,NaN,NaN
69,495.0,KBSTAR 국고채3년선물인버스,100060.0,100.0,-0.10%,0.0,3035.0,3033.0,0.00,6.0,NaN,NaN,NaN
73,496.0,KODEX 은행,7380.0,50.0,+0.68%,0.0,3033.0,41100.0,0.00,926132.0,NaN,NaN,NaN
74,497.0,삼영무역,16400.0,0.0,0.00%,500.0,3029.0,18467.0,20.55,8470.0,9.18,7.59,NaN
75,498.0,대한제분,178500.0,500.0,-0.28%,5000.0,3017.0,1690.0,8.80,14416.0,13.92,2.70,NaN
76,499.0,미원홀딩스,129500.0,500.0,-0.38%,500.0,3004.0,2320.0,0.93,1626.0,13.59,11.35,NaN
77,500.0,JW생명과학,18950.0,100.0,-0.52%,2500.0,3001.0,15835.0,4.06,27260.0,19.08,13.25,NaN

In [ ]:
#data.to_html('data/코스피500데이터html',encoding='cp949')

read_html이 정상적으로 실행되지 않는 경우\
read_html 문서 내에 테이블 형태의 데이터가 아닌 데이터 를 읽어고자 하는 경우\
웹사이트가 로딩되면서 데이터를 동적으로 읽어오는 경우\
->selenium이나 다른 라이브러리 사용

In [23]:
#삼성전자의 일별 시세 가져오기
삼성전자url = 'https://finance.naver.com/item/sise.nhn?code=005930'
data = pd.read_html(삼성전자url,encoding='cp949')
data[2]  #또다른 웹페이지 임베딩한 경우로 찾는 데이터 가져올 수 없음

        매도잔량     매도호가  Unnamed: 2     매수호가       매수잔량
0        NaN      NaN         NaN      NaN        NaN
1   164728.0  80200.0         NaN      NaN        NaN
2   102157.0  80100.0         NaN      NaN        NaN
3   294403.0  80000.0         NaN      NaN        NaN
4    79737.0  79900.0         NaN      NaN        NaN
5    33038.0  79800.0         NaN      NaN        NaN
6        NaN      NaN         NaN      NaN        NaN
7        NaN      NaN         NaN      NaN        NaN
8        NaN      NaN         NaN      NaN        NaN
9        NaN      NaN         NaN  79700.0   104435.0
10       NaN      NaN         NaN  79600.0   650514.0
11       NaN      NaN         NaN  79500.0  1116166.0
12       NaN      NaN         NaN  79400.0   381544.0
13       NaN      NaN         NaN  79300.0   320071.0
14       NaN      NaN         NaN      NaN        NaN

In [24]:
#삼성전자의 일별 시세 웹페이지 url로 변경
삼성전자url = 'https://finance.naver.com/item/sise_day.nhn?code=005930'
data = pd.read_html(삼성전자url,encoding='cp949')
data[2]  #또다른 웹페이지 임베딩한 경우로 찾는 데이터 가져올 수 없음
#/item/sise_day.nhn?code=005930

ValueError: No tables found

### 3) Selenium 라이브러리 활용  

* selenium 설치: conda install selenium
* chromedriver 다운로드 : https://sites.google.com/a/chromium.org/chromedriver/downloads

In [52]:
from selenium import webdriver

In [53]:
driver = webdriver.Chrome(executable_path=r'/Users/song-go-eun/Desktop/chromedriver')

In [54]:
driver.implicitly_wait(3)

In [55]:
driver.get(삼성전자url)

자동으로 웹페이지 띄워서 가져옴!

In [56]:
html =driver.page_source

In [59]:
data = pd.read_html(html, encoding='cp949')

In [60]:
삼성_일별 = data[0][data[0].날짜.notnull()]

            날짜       종가     전일비       시가       고가       저가         거래량
1   2021.07.16  79800.0   800.0  80100.0  80100.0  79500.0  10782325.0
2   2021.07.15  80600.0  1100.0  79800.0  80600.0  79500.0  13766279.0
3   2021.07.14  79500.0   300.0  79400.0  79600.0  79100.0  11575636.0
4   2021.07.13  79800.0   100.0  80000.0  80200.0  79800.0   9863450.0
5   2021.07.12  79700.0   300.0  79900.0  80000.0  79500.0   9768108.0
9   2021.07.09  79400.0   500.0  79600.0  79800.0  79000.0  22720577.0
10  2021.07.08  79900.0   900.0  81100.0  81200.0  79900.0  16660998.0
11  2021.07.07  80800.0   400.0  81200.0  81300.0  80300.0  15992202.0
12  2021.07.06  81200.0   800.0  80600.0  81200.0  80500.0  12131651.0
13  2021.07.05  80400.0   400.0  80100.0  80800.0  80000.0   8330969.0

In [68]:
#실습. 모든 기간의 삼성전자 일별 데이터를 스크래핑해서 하나의 데이터프레임으로 저장
일별주가 = []
삼성전자url = 'https://finance.naver.com/item/sise_day.nhn?code=005930&page='

for num in range(1,200):
    full_url= 삼성전자url+ str(num)
    driver.get(full_url)
    html=driver.page_source
    data = pd.read_html(html,encoding='cp949')
    삼성_일별 = data[0][data[0].날짜.notnull()]
    일별주가.append(삼성_일별)

In [69]:
삼성전자_일별_최종데이터 = pd.concat(일별주가)

In [70]:
삼성전자_일별_최종데이터

,날짜,종가,전일비,시가,고가,저가,거래량
1,2021.07.16,79800.0,800.0,80100.0,80100.0,79500.0,10782325.0
2,2021.07.15,80600.0,1100.0,79800.0,80600.0,79500.0,13766279.0
3,2021.07.14,79500.0,300.0,79400.0,79600.0,79100.0,11575636.0
4,2021.07.13,79800.0,100.0,80000.0,80200.0,79800.0,9863450.0
5,2021.07.12,79700.0,300.0,79900.0,80000.0,79500.0,9768108.0
...,...,...,...,...,...,...,...
9,2013.06.20,1329000.0,40000.0,1343000.0,1348000.0,1326000.0,356359.0
10,2013.06.19,1369000.0,18000.0,1382000.0,1385000.0,1364000.0,205405.0
11,2013.06.18,1387000.0,21000.0,1368000.0,1387000.0,1360000.0,220861.0
12,2013.06.17,1366000.0,3000.0,1370000.0,1378000.0,1365000.0,235169.0
13,2013.06.14,1369000.0,12000.0,1365000.0,1377000.0,1357000.0,351167.0

In [ ]:
#삼성전자_일별_최종데이터.to_excel('data/삼성전자_일별주가.xlsx',encoding='cp949')

## 4. 데이터베이스에서 읽기
### 파이썬에 내장(embedded)된 sqlite 사용

In [71]:
import sqlite3

In [72]:
#테이블 생성 SQL 정의
테이블생성 = 'CREATE TABLE locations \
                (a varchar[20], b varchar[20], c integer)'
#a,b,c 세개의 값을 가진 locations 테이블 생성

In [73]:
#sqlite 접속
conn = sqlite3.connect('temp.db')

In [74]:
#테이블 생성 SQL 수행 
conn.execute(테이블생성)

In [75]:
# commit() 수행. - SQL 수행 후, commit을 해야만, 데이터베이스에 SQL 구문이 적용됨 
conn.commit()

In [76]:
#생성된 테이블에 저장할 데이터 정의
data = [['서울','강남', 15]
       ,['서울','강동', 10]
       ,['서울','동대문', 7]
       ,['서울','양천', 12]
       ,['성남','분당', 12]
       ,['수원','영통', 15]
       ,['성남','중원', 11]
       ,['수원','팔달', 14]
       ]

In [77]:
# 데이터 적재 SQL 정의 
삽입 = 'insert into locations values (?,?,?)'

In [78]:
#데이터 적재 SQL 수행 
conn.executemany(삽입, data)

In [79]:
# commit() 수행 
conn.commit()

In [80]:
#Select SQL 실행1
pd.read_sql('select * from locations',conn)

    a    b   c
0  서울   강남  15
1  서울   강동  10
2  서울  동대문   7
3  서울   양천  12
4  성남   분당  12
5  수원   영통  15
6  성남   중원  11
7  수원   팔달  14

In [81]:
#Select SQL 실행2
pd.read_sql('select a, sum(c) from locations group by a', conn)

    a  sum(c)
0  서울      44
1  성남      23
2  수원      29

In [82]:
# 데이터베이스의 테이블 크기가 큰 경우에는 cursor 사용하기
cursor = conn.execute('select * from locations')

In [84]:
cursor.fetchmany(3)

[('서울', '동대문', 7), ('서울', '양천', 12), ('성남', '분당', 12)]

In [91]:
cursor.close()